# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_corrcperm', [dirname(__file__)])
        except ImportError:
            import _corrcperm
            return _corrcperm
        if fp is not None:
            try:
                _mod = imp.load_module('_corrcperm', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _corrcperm = swig_import_helper()
    del swig_import_helper
else:
    import _corrcperm
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class corrcperm(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, corrcperm, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, corrcperm, name)
    __repr__ = _swig_repr
    __swig_getmethods__["genes"] = _corrcperm.corrcperm_genes_get
    if _newclass:genes = _swig_property(_corrcperm.corrcperm_genes_get)
    __swig_getmethods__["cols"] = _corrcperm.corrcperm_cols_get
    if _newclass:cols = _swig_property(_corrcperm.corrcperm_cols_get)
    def __init__(self, *args): 
        this = _corrcperm.new_corrcperm(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _corrcperm.delete_corrcperm
    __del__ = lambda self : None;
    def data_set(self, *args): return _corrcperm.corrcperm_data_set(self, *args)
    def makerandomdata(self, *args): return _corrcperm.corrcperm_makerandomdata(self, *args)
    def permutevecset(self, *args): return _corrcperm.corrcperm_permutevecset(self, *args)
    def makepvec(self, *args): return _corrcperm.corrcperm_makepvec(self, *args)
    def Nstat(self, *args): return _corrcperm.corrcperm_Nstat(self, *args)
    def calculategroupsums(self): return _corrcperm.corrcperm_calculategroupsums(self)
    def Nstat3(self, *args): return _corrcperm.corrcperm_Nstat3(self, *args)
    def allNstats(self, *args): return _corrcperm.corrcperm_allNstats(self, *args)
    def getNstat(self, *args): return _corrcperm.corrcperm_getNstat(self, *args)
    def rearrangeall(self): return _corrcperm.corrcperm_rearrangeall(self)
    def threadedallNstats(self, *args): return _corrcperm.corrcperm_threadedallNstats(self, *args)
    def ignoregene(self, *args): return _corrcperm.corrcperm_ignoregene(self, *args)
corrcperm_swigregister = _corrcperm.corrcperm_swigregister
corrcperm_swigregister(corrcperm)



